<?php

/**
 * @file
 * Contains node_generated_updated.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_generated_updated_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the node_generated_updated module.
    case 'help.page.node_generated_updated':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('an updated node generator module') . '</p>';
      return $output;

    default:
  }
}
